version: '3.3'
services:
  app1:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        APP: app1
        APP_PORT: 3101
    tty: true
  app2:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        APP: app2
        APP_PORT: 3101
    tty: true