version: '3.3'
services:
  app:
    container_name: fusebox_app
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/usr/node/app
      - /usr/node/app/node_modules
      - /usr/node/app/.fusebox
    ports:
      - "4444:4444"
    tty: true