#!/bin/sh

sv up app || exit 1;
source /etc/envvars;
kill `ps -ef | grep 'inotifywait -m -r -e moved_to -e close_write -e attrib --format "%e %w%f" /usr/node/$APP/packages/node_modules/monorepo-lib/dist/index.cjs.js' | awk '{print $1}'`;
inotifywait -m -r -e moved_to -e close_write -e attrib --format "%e %w%f" /usr/node/$APP/packages/node_modules/monorepo-lib/dist/index.cjs.js |
  while read evt dir file; do
      # echo "Event: $evt, Dir: $dir, File: $file"
      # echo "Fullpath: $dir $file" #note the space between $dir and $file
      sv restart app
  done
