version: '3.3'
services:
  app:
    container_name: monorepo-container
    build:
      context: ./
    volumes:
      - ./:/usr/node/app
      - /usr/node/app/.fusebox
      - /usr/node/app/cache
      - /usr/node/app/node_modules
    ports:
      - "4444:4444"
    tty: true