version: '3.3'
services:
  app1:
    build:
      context: ./
      dockerfile: ./app1/Dockerfile
    volumes:
      - ./app1:/usr/node/app1
      - ./core:/usr/node/core
    ports:
      - "3101:80"
    tty: true