version: '3.3'
services:
  app:
    container_name: docker-with-common-config_blank_fe_app
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/usr/node/app
      - /usr/node/app/node_modules
    ports:
      - "3101:80"
    tty: true